program: train.py
method: grid
metric:
  goal: minimize
  name: val_loss
parameters:
  Acceptor:
    lr: [1e-4, 1e-5, 1e-8]
    hidden_dim: [32, 64, 128]
  Encoder:
    lr: [1e-4, 1e-5, 1e-8]
    layers: [2, 4, 8]
    heads: [1, 2, 4]
  CausalEncoder:
    lr: [1e-4, 1e-5, 1e-8]
    num_heads: [2, 4, 8]
    hidden_size: [96, 128, 148]
    num_layers: [1, 3, 5]
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27